name: Deploy

on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui --skip-manifest-update

      - name: Restore
        run: dotnet restore
        working-directory: ./Calcultor  

      - name: Build
        run: dotnet build -c Release -f:net9.0-windows10.0.19041.0

      - name: Test
        run: dotnet test -c Realease -f:net9.0-windows10.0.19041.0
        working-directory: ./Calcultor

      - name: Publish
        run: dotnet publish -c Realease -f:net9.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true
        working-directory: ./Calcultor

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./Calculator/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix
